name: PHALP
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.5.30=py37h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - fontconfig=2.13.1=h6c09931_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.3.0=h06a4308_3350
  - jasper=2.0.14=hd8c5072_2
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglu=9.0.0=hf484d3e_1
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.1=h27cfd23_0
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h27cfd23_0
  - pcre=8.45=h295c915_0
  - pip=21.1.3=py37h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - py-opencv=3.4.2=py37hb342d67_1
  - python=3.7.10=h12debd9_4
  - pytorch=1.9.0=py3.7_cuda10.2_cudnn7.6.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.9.0=py37
  - torchvision=0.2.1=py37_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - asttokens==2.0.5
    - attrs==21.2.0
    - backcall==0.2.0
    - black==21.4b2
    - boto3==1.20.48
    - botocore==1.23.48
    - cachetools==4.2.4
    - charset-normalizer==2.0.2
    - chumpy==0.70
    - click==8.0.1
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - configparser==5.0.2
    - cycler==0.10.0
    - cython==0.29.24
    - decorator==4.4.2
    - deprecated==1.2.13
    - docker-pycreds==0.4.0
    - dotmap==1.3.26
    - einops==0.3.0
    - executing==0.8.0
    - ffmpeg==1.4
    - ffmpeg-python==0.2.0
    - filelock==3.4.2
    - flake8==3.9.2
    - flake8-import-order==0.18.1
    - freetype-py==2.2.0
    - future==0.18.2
    - fvcore==0.1.5.post20211023
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - hydra-core==1.1.1
    - icecream==2.1.1
    - idna==3.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.6.1
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - iopath==0.1.9
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jmespath==0.10.0
    - joblib==1.0.1
    - jsonschema==4.4.0
    - kiwisolver==1.3.1
    - llvmlite==0.38.0
    - markdown==3.3.6
    - matplotlib==3.2.1
    - matplotlib-inline==0.1.2
    - mccabe==0.6.1
    - meshzoo==0.9.3
    - more-itertools==8.12.0
    - motmetrics==1.2.0
    - moviepy==0.2.3.5
    - msgpack==1.0.3
    - mypy-extensions==0.4.3
    - natsort==8.1.0
    - networkx==2.5.1
    - numba==0.55.1
    - numpy==1.18.1
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-contrib-python==4.5.3.56
    - opencv-python==4.4.0.46
    - packaging==21.0
    - pandas==1.3.0
    - parso==0.8.2
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.2
    - pluggy==0.13.1
    - portalocker==2.3.2
    - promise==2.3
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py==1.10.0
    - py-cpuinfo==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pycodestyle==2.7.0
    - pydot==1.4.2
    - pyflakes==2.3.1
    - pyglet==1.5.18
    - pygments==2.9.0
    - pyopengl==3.1.0
    - pyparsing==2.4.7
    - pyrender==0.1.45
    - pyrsistent==0.18.1
    - pytest==6.0.1
    - pytest-benchmark==3.4.1
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - ray==1.10.0
    - redis==4.1.3
    - regex==2021.11.10
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - s3transfer==0.5.1
    - scikit-image==0.16.2
    - scikit-learn==0.22.2
    - scipy==1.4.1
    - sentry-sdk==1.3.0
    - shortuuid==1.0.1
    - sklearn==0.0
    - smmap==4.0.0
    - subprocess32==3.5.4
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - threadpoolctl==2.2.0
    - tifffile==2021.7.2
    - toml==0.10.2
    - tqdm==4.61.2
    - traitlets==5.0.5
    - trimesh==3.9.23
    - typed-ast==1.5.1
    - urllib3==1.26.6
    - wandb==0.12.0
    - wcwidth==0.2.5
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - xmltodict==0.12.0
    - yacs==0.1.8
    - youtube-dl==2021.12.17
    - zipp==3.5.0


